os:
    - osx
    - linux
language: cpp
compiler: g++
script:
    - mkdir build && cd build
    - g++ -std=c++0x -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"lintcode/lintcode.d" -MT"lintcode/lintcode.o" -o "lintcode/lintcode.o" "../lintcode/lintcode.cpp"
    - g++ -std=c++0x -o "main"  ./lintcode/medium/102.linked-list-cycle.o ./lintcode/medium/105.copy-list-with-random-pointer.o ./lintcode/medium/106.convert-sorted-list-to-binary-search-tree.o ./lintcode/medium/11.search-range-in-binary-search-tree.o ./lintcode/medium/124.longest-consecutive-sequence.o ./lintcode/medium/15.permutations.o ./lintcode/medium/16.permutations-ii.o ./lintcode/medium/17.subsets.o ./lintcode/medium/170.rotate-list.o ./lintcode/medium/191.maximum-product-subarray.o ./lintcode/medium/3.digit_counts.o ./lintcode/medium/4.ugly-number-ii.o ./lintcode/medium/5.kth-largest-element.o ./lintcode/medium/7.serialize-and-deserialize-binary-tree.o ./lintcode/medium/92.backpack.o ./lintcode/medium/95.validate-binary-search-tree.o ./lintcode/medium/98.sort-list.o ./lintcode/medium/99.reorder-list.o  ./lintcode/hard/121.word-laddder-ii.o ./lintcode/hard/20.diced-sum.o ./lintcode/hard/24.lfu-cache.o ./lintcode/hard/43.maximum-subarray-iii.o ./lintcode/hard/65.median-of-two-sorted-arrays.o ./lintcode/hard/87.remove-node-in-binary-search-tree.o  ./lintcode/easy/1.a-b-problem.o ./lintcode/easy/112.remove-duplicates-from-sorted-list.o ./lintcode/easy/114.unique-paths.o ./lintcode/easy/115.unique-paths-ii.o ./lintcode/easy/165.merge-two-sorted-lists.o ./lintcode/easy/174.remove-nth-node-from-end-of-list.o ./lintcode/easy/41.maximum-subarray.o ./lintcode/easy/69.binary-tree-level-order-traversal.o ./lintcode/easy/85.insert-node-in-a-binary-search-tree.o ./lintcode/easy/93.balanced-binary-tree.o ./lintcode/easy/96.partition-list.o ./lintcode/easy/97.maximum-depth-of-binary-tree.o  ./lintcode/lintcode.o
before_deploy:
    - git config --local user.name "Aaron Liu"
    - git config --local user.email "aaronliu0130@gmail.com"
    - export TRAVIS_TAG=$(git log --format=%H -1)
    - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: "6827807f0febef3b5d7d80adc632b05b3d0f69e7"
  file:
    - "main"
  skip_cleanup: true
  on:
    tags: true

